### PR TITLE
Made thermometer widget movable by use of shift-click and dragging

### PR DESCRIPTION
**Pull request by ChrisF-127**
This feature had been requested by a few users. Thought it neat to add it.

Added new options for this functionality, translations for languages other than English will have to be updated accordingly. Sadly I don't speak any of the currently available translation languages.

(Also, the merging between my branch and the main branch looks a bit weird, I hope it's all fine, a bit unsure why my commits appear on the main branch and my fork. I'm still quite new to using GitHub.)

### CODE REVIEW

**Comment by Falconne** [comment]
Thanks for this, sorry about not being able to get to these sooner. There is a conflict, could you resolve it and I'll do an update.

**Comment by ChrisF-127** [comment]
It says for me that there are no conflicts with the base branch. Unless I'm missing something, it should be fine to merge.

**Comment by Falconne** [comment]
It doesn't let me merge:

image

I think you have to pull my master branch into your feature branch so you can see the conflict, e.g. (while in your branch):
```
git remote add falconne https://github.com/Falconne/HeatMap.git
git pull falconne master
```

or `git pull --rebase falconne master` to keep the history clean, but if you do that remember the "ours" and "theirs" is flipped around during conflict resolution.

If that doesn't work I can resolve the conflict, it's just taking me a while to find time for these.

**Comment by ChrisF-127** [comment]
Very strange, it definitely tells me there are no conflicts and there are no changes to pull/merge either.

Screenshot 2021-10-24 232143


Probably would have been fine had I started a new branch after my previous edit got merged though, as it caused my commits to appear twice, interestingly enough. Wouldn't surprise me, if that causes some issues. It's likely that, due to not having worked much with Git and especially GitHub so far, I did something wrong here...

Screenshot 2021-10-24 232101

In all honesty, I'm unsure what to do here or how to fix it. I had expected it to be mergable without issues.

**Comment by Falconne** [comment]
No worries I'll sort it out. Will try to do it this Saturday.

**Comment by Falconne** [comment]
@XT-0xFF Finally got around to publishing this, sorry it took so long. Do you still want to take on maintenance of this mod? I can look into adding you to the Github repo and the workshop page.

**Comment by ChrisF-127** [comment]
@Falconne I'd gladly help maintain this mod.

Saw people say that, maybe since this update, their button is not showing up anymore. Wonder if there's some issue or incompatibility I overlooked. 
If they see I worked on this, they might even answer my questions so I can look into the problem...

**Comment by Falconne** [comment]
Thanks, I've invited you to the repo. After accepting try creating a branch and see if it lets you push it. On Steam I need you as a contact to add you as a contributor to the mod so have sent you an invite.

Yeah I saw the recent comments. Probably a good idea to put it on top of the help as you say. Also, when the default settings values for position are being decided (for when someone installs this mod for the first time), I think it's a good idea to see if the help is enabled and if so default the margin to the same location that it previously showed, next to the help. If someone installs the mod and this displays on top of the help, it would be a bit weird and they might not know they can drag it with Shift. I've updated the description now to include Shift dragging, but not everyone reads the description.

**Comment by Falconne** [comment]
Ok I've added you as a contributor on the workshop page too

**Comment by ChrisF-127** [comment]
Thank you for your trust!

I'll look into the "widget-on-top"-issue on the weekend or next week probably.
Moving the widget next to the help ledger also makes sense on first-time start up. Shouldn't be too hard to implement.

**Pull request merged**
