### PR TITLE
Version Update for 1.1

### PR DESCRIPTION
**Pull request by NGDDev**
Changed the version in Version.xml to 6.2.0
Changed the version in Packages.config to 6.2.0
Incremented Version # by 0.0.1 in AssemblyInfo.cs

### CODE REVIEW

**Comment by Falconne** [comment]
Thanks. I think we also need to update `<supportedVersions>` in `About.xml`.

**Comment by NGDDev** [comment]
You are right, forgot to change that one. I couldn't get it to build on my end was hoping with these changes you could rebuild on your end and re upload to workshop. That's if we have all that needs changing

**Comment by Falconne** [comment]
Yep, I can do the change and test after merging the pull request. Been meaning to do all my mods, just been very busy lately. Probably get to it on the weekend.

What problem did you have with the build?

**Comment by NGDDev** [comment]
After following the readme and doing the manual changes to x files. Upon doPreBuild it was still telling me "Rimworld installation not found; see Readme ....."

**Pull request merged**
