### PR TITLE
Pull request: Update Japanese Translation for v1.3.17

### PR DESCRIPTION
**Pull request by Proxyer**
- Add new widget mod options.

I am sorry for the delay in noticing the addition.

### CODE REVIEW

**Comment by Falconne** [comment]
@XT-0xFF Can you merge this as well when you fix the "widget behind help" bug? This is a Japanese translation to the new settings you added.

**Comment by Proxyer** [comment]
Thank you merged!

**Comment by Proxyer** [comment]
Thank you for merged.

**Comment by Proxyer** [comment]
Yes. This pull request has a Japanese translation with the new Mod option added in Heat map version 1.3.17 updated on October 31st.

- add fixed ShowTemperatureOverRoomsDesc translation part.

**Comment by ChrisF-127** [comment]
Yes, will be merged when the "widget behind help" bug is fixed. 
Sadly isn't as easy as I thought, from what I gathered so far, will probably take till the weekend until I find some time to really look into it.

**Comment by Proxyer** [comment]
Thank you!

**Comment by ChrisF-127** [comment]
Merged!

Small note, though, I modified "FALCHM.ThermometerTooltip" in the last update and added a line about the position being lockable via mod settings.

**Comment by Proxyer** [comment]
Thank you merged!
I understand about the addition. I will check immediately and send the required translations.

**Pull request merged**
